# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import numpy as np

In [3]:
data = np.random.uniform(0, 20, size=(4, 7))
print(data, end="\n\n")

(data-np.min(data)) / (np.max(data)-np.min(data))

[[16.80578477  8.5526949  16.09422484  1.28416393 14.16894145  2.88569845
  14.86488348]
 [12.4351037  10.46122937 14.13402667 12.02409294  1.35346654  7.79894244
  10.23914488]
 [ 4.06716928  3.34729979  3.9311781  12.70568392 19.64325655  5.37657921
  13.62344106]
 [ 6.16789804 18.40622149  3.783002   19.74817978 15.87131807  9.59852148
  12.96459402]]



array([[0.84064165, 0.39365927, 0.802104  , 0.        , 0.69783181,
        0.08673815, 0.73552361],
       [0.6039282 , 0.49702435, 0.69594084, 0.5816681 , 0.00375339,
        0.35283649, 0.48499639],
       [0.1507259 , 0.1117382 , 0.1433607 , 0.61858266, 0.99431742,
        0.22164275, 0.66828783],
       [0.2645001 , 0.92732035, 0.13533557, 1.        , 0.7900315 ,
        0.45030061, 0.63260507]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [4]:
arr = np.random.randint(0, 10, size=(8, 10))
print(arr)

print("Row Index", np.argmin(np.sum(arr, axis=1)))
arr[np.argmin(np.sum(arr, axis=1))]

[[1 9 8 1 7 5 3 4 3 4]
 [6 6 5 9 4 4 6 6 0 0]
 [9 5 3 6 5 3 6 0 9 9]
 [7 3 5 7 2 0 8 0 4 0]
 [8 8 9 6 1 5 0 3 1 1]
 [8 1 0 6 0 1 8 1 9 3]
 [8 2 6 0 4 0 0 6 4 0]
 [5 4 1 4 7 1 3 1 2 9]]
Row Index 6


array([8, 2, 6, 0, 4, 0, 0, 6, 4, 0])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [5]:
point_1 = np.random.randint(0, 20, size=5)
point_2 = np.random.randint(0, 20, size=5)
print(point_1)
print(point_2)
#first way
square = np.square(point_1 - point_2)
sum_square = np.sum(square)
print(np.sqrt(sum_square))
#second way
distance = np.linalg.norm(point_1-point_2)
print(distance)

[17  1 13 13 11]
[17  2 11 19  6]
8.12403840463596
8.12403840463596


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [6]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
#x = a^-1*(-c)*b^-1

x0 = np.matmul(np.linalg.inv(a),(-c))
print(x0)
x =  np.matmul(x0,np.linalg.inv(b))
print(x)

[[ 3. -1.]
 [-4.  3.]
 [ 1. -7.]]
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [7]:
data = np.loadtxt("minutes_n_ingredients.csv", delimiter=',', skiprows=1, dtype=np.int32)
# first 5 rows
data[0:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [8]:
#делаем срез массива, извлекаем все, кроме первого массива
sliced = data[:, 1:]

# находим среднее по столбцам среза
print(np.mean(sliced, axis=0))
# находим минимум по столбцам среза
print(np.min(sliced, axis=0))
# находим максимум по столбцам среза
print(np.max(sliced, axis=0))
# находим медиану по столбцам среза
print(np.median(sliced, axis=0))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [9]:
# np.clip(data[:, 1], 0, np.quantile(data[:, 1], 0.75, method='higher')) #вариант с семинара

quant = np.quantile(data[:, 1], 0.75)
cropped_data = data[ data[: , 1] < quant]
print(cropped_data)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [10]:
#считает количество нулевых значений
print(np.count_nonzero(data[:, 1] == 0))

#заменяем нулевые значения единицей
np.place(data, data==0, 1)

#проверяем, не осталось ли нулей
#(Да, можно и через np.count_nonzero, но надо попробовать всё)
data[np.argsort(data[:, 1])]

479


array([[      4896,          1,         14],
       [      6975,          1,          8],
       [      3492,          1,          7],
       ...,
       [    425681,     259205,          2],
       [    216215,     259260,          7],
       [    261647, 2147483647,          8]], dtype=int32)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [11]:
#уникальные рецепты - это рецепты, у которых не повторяются минуты и количество ингредиентов
len(np.unique(sliced, axis=0))

4183

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [12]:
print(np.unique(data[:, 2], axis=0))
print(np.unique(data[:, 2], axis=0).size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [13]:
under_five_data = data[data[:, 2] < 5]
under_five_data

array([[204134,      5,      3],
       [ 25623,      6,      4],
       [484223,     18,      4],
       ...,
       [227056,     30,      4],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [14]:
mean_ingredients_per_min = data[:, 2] / data[:, 1]
np.max(mean_ingredients_per_min)

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [15]:
top_sorted_data = data[data[:, 1].argsort()[::-1]][:100]

np.mean(top_sorted_data[:,2])

data[:, 1].argsort()

array([89843,  1740, 28278, ..., 76939, 39484, 15653])

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [16]:
arg_id = np.where(data[:, 0] > -1)[0] #получаем индексы всех элементов первого столбца
rand_idx = np.random.choice(arg_id, size=10, replace=False) #выбирает 10 случайных

data[rand_idx]

array([[200314,     20,      8],
       [ 59504,     55,     16],
       [248857,     45,      7],
       [179325,     40,      6],
       [358488,     30,      6],
       [464540,     30,     14],
       [370976,     70,     12],
       [377252,     45,     12],
       [ 27637,      5,     11],
       [ 22292,     35,      9]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [17]:
mean_ing = np.mean(data[:, 2], axis=0)
under_mean_ing_data = data[data[:, 2] < mean_ing]

(np.shape(under_mean_ing_data)[0] * 100) / np.shape(data)[0]

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [18]:
is_simple = np.where((data[:, 1] < 20) & (data[:, 2] <= 5) , 1, 0)
extended_data = np.column_stack((data, is_simple))
extended_data

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [19]:
(np.shape(extended_data[extended_data[:, 3] == 1])[0] * 100) / np.shape(data)[0]

8.315

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [28]:
simple = data[data[:, 1] <= 10]
standard = data[(data[:, 1] > 10) & (data[:, 1] <= 20)]
hard = data[data[:, 1] > 20]

min_shape = np.min((np.shape(simple)[0], np.shape(standard)[0], np.shape(hard)[0]))
data_cube = np.stack([
    simple[:min_shape],
    standard[:min_shape],
    hard[:min_shape],
])

data_cube

(12466, 3)
(14184, 3)
(73350, 3)


array([[[ 94746,     10,      6],
        [ 67660,      5,      6],
        [366174,      7,      9],
        ...,
        [420725,      5,      3],
        [  4747,      1,      9],
        [370915,      5,      4]],

       [[ 33941,     18,      9],
        [446597,     15,      5],
        [ 74205,     20,      7],
        ...,
        [230115,     20,      7],
        [496131,     20,      9],
        [365818,     20,      6]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [ 68428,     70,     10],
        [312995,   1445,      7],
        [ 93651,    240,     12]]], dtype=int32)